[env:esp32dev]
platform = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF5
; IDF 5.1.4
; platform = espressif32 @ ^6.8.1 
board = esp32dev
; platform_packages =
    ; framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.16 
    ; framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.4  BUG KeyError: 'framework-arduinoespressif32-libs':
    ; framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#e70f4d3819500151af6a0adda561f09f647b3fc7
    ;3.X.X SimpleFOC need espidf5.2+

framework = arduino
monitor_speed = 115200

build_flags = 
    ; -DCONFIG_BT_ENABLED=1
    ; -DCONFIG_BLUEDROID_ENABLED=1
    -D CORE_DEBUG_LEVEL=5
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -I lib/simple_foc_module/src
    -I lib/uart_protocol/src
    
    -Os

; # 添加以下行来包含 lib/cus/simple_foc_module/ 目录中的源文件
; src_filter = 
;     +<*>
;     +<../lib/cus/simple_foc_module/*.cpp>




upload_speed = 921600
; upload_speed = 9600
lib_deps = 
    SPI
    Wire
    bblanchon/ArduinoJson@^6.19.4  ; 用於JSON數據的解析和生成
    olikraus/U8g2@^2.33.15         ; 用於OLED顯示器控制
    esp32-BLE-Arduino              ; ESP32 BLE功能庫
    BluetoothSerial                ; 用於經典藍牙串口通信
    BLE                            ; 用於BLE（低功耗藍牙）通信
    ; WIFI
    ; https://github.com/micro-ROS/micro_ros_platformio#25ab6593ad0c25ce32342a86fa1ac3d7998f90f0
    https://github.com/simplefoc/Arduino-FOC#v2.3.4

; board_microros_transport = wifi
board_build.partitions = huge_app.csv